### ISSUE TITLE
Erro ao executar npm start

### ISSUE THREAD

**Issue by esterlilianlb** [fabifelicia/case-pipo#1]
Oi Fabiana, tudo bem? Muito obrigada por se inscrever no nosso processo seletivo :)

Eu tentei rodar o projeto seguindo as instruções do `readme`, mas quando rodei o `npm start` recebi esse erro aqui:
```
npm ERR! missing script: start
```
Depois tentei fazer um `npm run dev` também mas voltou um outro erro:
```
(node:17905) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/esterbenitah/Documents/hiring/case-pipo/src/routes/clients.route.js:1
import { Router } from 'express'
         ^^^^^^
SyntaxError: The requested module 'express' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'express';
const { Router } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:136:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```
Tem algo mais que eu preciso executar ou confirgurar do meu lado? Você consegue me ajudar?
Obrigada!

**Comment by fabifelicia** [comment]
Boa tarde Ester
Desculpe-me mas não incluí o script start. Por favor, veja se vc consegue agora o npm start

**Comment by esterlilianlb** [comment]
Com a adição do script start agora está dando esse erro:
```
sh: src/index.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! pipo-back@1.0.0 start: `src/index.js`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the pipo-back@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by fabifelicia** [comment]
Oi Ester
Acho que o problema e o arquivo .env que precisa ser configurado por vc. precisa definir porta e string para conexao com o banco de dados.

**Comment by esterlilianlb** [comment]
Entendi. É que não tem esse arquivo aqui, acho que como tá no .gitignore não subiu pro repositório. 
Como que ele precisa ser preenchido?

**Comment by fabifelicia** [comment]
Na raiz do projeto vai criar um arquivo chamado .env
Dentro dele vai colocar essas credenciais:
CONNECTION_API=string_banco_dados (aqui eu criei uma conta no ElephantSQL e colei a string aqui)
PORT=numero_porta

Se vc preferir, posso enviar por email as minhas credenciais do banco para testar. So nao posso colocar no git pq viola as condiçoes.

**Comment by esterlilianlb** [comment]
Ah, você consegue me mandar então?

**Comment by fabifelicia** [comment]
Mande seu email

**Comment by esterlilianlb** [comment]
ester.benitah@piposaude.com.br

**Comment by fabifelicia** [comment]
Vou enviar e atualizar o package.json e o README
